/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "loginrpc.h"

bool_t
xdr_credpair (XDR *xdrs, credpair *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->uname, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->password, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultpair (XDR *xdrs, resultpair *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->returnCode))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->userCount))
		 return FALSE;
	return TRUE;
}
