/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOGINRPC_H_RPCGEN
#define _LOGINRPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct credpair {
	char uname[256];
	char password[256];
};
typedef struct credpair credpair;

struct resultpair {
	int returnCode;
	int userCount;
};
typedef struct resultpair resultpair;

#define LOGIN_PROG 0x20000008
#define LOGIN_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LOGIN 1
extern  resultpair * login_1(credpair *, CLIENT *);
extern  resultpair * login_1_svc(credpair *, struct svc_req *);
extern int login_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LOGIN 1
extern  resultpair * login_1();
extern  resultpair * login_1_svc();
extern int login_prog_1_freeresult ();
#endif /* K&R C */

#define REGISTER_PROG 0x20000088
#define REGISTER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define REGISTER 1
extern  resultpair * register_1(credpair *, CLIENT *);
extern  resultpair * register_1_svc(credpair *, struct svc_req *);
extern int register_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define REGISTER 1
extern  resultpair * register_1();
extern  resultpair * register_1_svc();
extern int register_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_credpair (XDR *, credpair*);
extern  bool_t xdr_resultpair (XDR *, resultpair*);

#else /* K&R C */
extern bool_t xdr_credpair ();
extern bool_t xdr_resultpair ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOGINRPC_H_RPCGEN */
