/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "loginrpc.h"


void
login_prog_1(char *host)
{
	CLIENT *clnt;
	resultpair  *result_1;
	credpair  login_1_arg;

	clnt = clnt_create (host, LOGIN_PROG, LOGIN_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	char username[256];
	char password[256];
	int uvalid = 0;
	int pvalid = 0;	
	while(uvalid == 0){
		printf("Please enter username: ");
		scanf("%s",username);
		if(username != ""){
			uvalid=1;
		}
	}
	while(pvalid == 0){
		printf("Please enter password: ");
		scanf("%s",password);
		if(password != ""){
			pvalid=1;
		}
	}
	//printf("Username: %s\n",username);
	//printf("Password: %s\n",password);
	strcpy(login_1_arg.uname,username);
	strcpy(login_1_arg.password,password);
	//printf("In login method\n");
	result_1 = login_1(&login_1_arg, clnt);
	if (result_1 == (resultpair *) NULL) {
		clnt_perror (clnt, "call failed");
	}else if(result_1->returnCode == 1) {
		printf("Welcome %s!!\n",username);
		if(strcmp(username,"admin") == 0){
			printf("The users registered are: %d\n",result_1->userCount);
		}
		exit(0);
	}else if(result_1->returnCode == 0) {
		printf("Invalid Login. Please try again.\n");
		exit(0);
	}else {
		exit(0);
	}

	clnt_destroy (clnt);

}


void
register_prog_1(char *host)
{
	CLIENT *clnt;
	resultpair  *result_1;
	credpair  register_1_arg;
	char opt[1];
	clnt = clnt_create (host, REGISTER_PROG, REGISTER_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	char username[256];
	char password[256];
	int uvalid = 0;
	int pvalid = 0;	
	while(uvalid == 0){
		printf("Please enter username: ");
		scanf("%s",username);
		if(username != ""){
			uvalid=1;
		}
	}
	while(pvalid == 0){
		printf("Please enter password: ");
		scanf("%s",password);
		if(password != ""){
			pvalid=1;
		}
	}
	//printf("Username: %s\n",username);
	//printf("Password: %s\n",password);
	strcpy(register_1_arg.uname,username);
	strcpy(register_1_arg.password,password);
	result_1 = register_1(&register_1_arg, clnt);
	if (result_1 == (resultpair *) NULL) {
		clnt_perror (clnt, "call failed");
	}else if (result_1->returnCode == 0) {
		printf("User already exists. Please try with a new user name.\n");
		exit(0);
	}else if (result_1->returnCode == 1) {
		printf("User creation Successful.\nDo you want to login?[y/n]:");
		scanf("%s",&opt);
		if(strcmp("Y",opt)==0 || strcmp("y",opt)==0) {
			login_prog_1(host);
		} else {
			exit(0);
		}
		
	}

	clnt_destroy (clnt);

}


int
main (int argc, char *argv[])
{
	char *host;
	int choice = 0;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
		while(choice != 3){
		printf("Welcome!!\nPlease choose an option to continue:\n1. Register\n2. Login\n3. Exit\n");
		scanf("%d",&choice);
		switch(choice){
			case 1:
				register_prog_1 (host);
				break;
			case 2: 
				login_prog_1 (host);
				break;
			case 3:
				break;	
			default:
				printf("Invalid Option entered. System exiting\n");
				choice=3;
				break;
		}
	}

exit (0);
}
