/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "loginrpc.h"

// Helper Function to get curremt directory

char *getDirectory(){
	printf("LOG: getting current directory\n");
	char cwd[1024];
   	getcwd(cwd, sizeof(cwd));
	strcat(cwd,"/");
	printf("LOG: exiting current directory\n");
	return (char *)cwd;
}

// Helper function to verify the already existing user name

int isExistinguser(credpair *creds) {
	printf("LOG: Existing User validation begin\n");
	char * line = NULL;
	size_t len = 0;
	ssize_t read;
	FILE *fp;
	char data[256];
	strcpy(data,creds->uname);
	strcat(data,"\n");
	char *dir = getDirectory();
	strcat(dir,"users.db");
	
	fp = fopen(dir,"r");
	int existingUser = 0;
	if (fp == NULL) {
		printf("fp null\n");
		printf("LOG: Existing User validation end\n");
		return existingUser;
	}
	while((read = getline(&line,&len,fp))!= -1){
		
		if (strcmp(line,data) == 0) {
			printf("LOG: User exists\n");
			existingUser = 1;
			break;
		}
	}
	fclose(fp);
	if(line) {
		free(line);
	}
	printf("LOG: Existing User validation end\n");
	return existingUser;
}

// Check validity of user

int isValidUser(credpair *creds) {
	printf("LOG: Validating user begin\n");
	char * line = NULL;
	size_t len = 0;
	ssize_t read;
	FILE *fp;
	char data[514] = "";
	strcpy(data,creds->uname);
	strcat(data,"#");
	strcat(data,creds->password);
	strcat(data,"\n");
	char *dir = getDirectory();
	strcat(dir,"credentials.db");
	fp = fopen(dir,"r");
	int validUser = 0;
	if (fp == NULL) {
		printf("fp null\n");
		printf("LOG: Validating user done.\n");
		return validUser;
	}
	while((read = getline(&line,&len,fp))!= -1){
		
		if (strcmp(line,data) == 0) {
			printf("LOG: Valid User\n");
			validUser = 1;
			break;
		}
	}
	fclose(fp);
	if(line) {
		free(line);
	}
	printf("LOG: Validating user done.\n");
	return validUser;
	
}

// Helper function to count number of users

int getLineCount() {
	printf("LOG: line count begin\n");
	int count = 0;
	char * line = NULL;
	size_t len = 0;
	ssize_t read;
	FILE *fp;
	char *dir = getDirectory();
	strcat(dir,"users.db");
	fp = fopen(dir,"r");
	if (fp == NULL) {
		printf("fp null\n");
		printf("LOG: line count end\n");
		return count;
	}
	while((read = getline(&line,&len,fp))!= -1){
		count++;
	}
	fclose(fp);
	if(line) {
		free(line);
	}
	printf("LOG: line count end\n");
	return count;
}

// Helper function to add a user to db

void addUser(credpair *argp) {
	printf("LOG: Adding user begin\n");
	char *dir = getDirectory();
	char userdir[1024]="";
	strcpy(userdir,dir);
	strcat(userdir,"users.db");
	FILE *fp=fopen(userdir,"a");
	if(fp != NULL) {
		char user_data[256] = "";
		strcpy(user_data,argp->uname);
		strcat(user_data,"\n");
		fputs(user_data,fp);
		printf("LOG: User added\n");
		fclose(fp);
	}
	char creddir[1024]="";
	strcpy(creddir,dir);
	strcat(creddir,"credentials.db");
	fp = fopen(creddir,"a");
	if(fp != NULL) {
		char cred_data[514] = "";
		strcpy(cred_data,argp->uname);
		strcat(cred_data,"#");
		strcat(cred_data,argp->password);
		strcat(cred_data,"\n");
		fputs(cred_data,fp);
		printf("LOG: Credentials added\n");
		fclose(fp);
	}
	printf("LOG: Adding user end\n");
}

// Login function 

resultpair *
login_1_svc(credpair *argp, struct svc_req *rqstp)
{
	printf("LOG: login begin\n");
	static resultpair  result;
	int validUser = 0;
	int users = 0;
	validUser = isValidUser(argp);
	if(validUser == 1) {
		users = getLineCount();
		result.returnCode = 1;
		result.userCount = users;
	} else {
		result.returnCode = 0;
	}
	printf("LOG: login end\n");	
	return &result;
}

// Register function

resultpair *
register_1_svc(credpair *argp, struct svc_req *rqstp)
{
	printf("LOG: Register method begin\n");
	static resultpair  result;
	int existUser = isExistinguser(argp);
	if(existUser == 1) {
		result.returnCode = 0;	
	}else {
		addUser(argp);
		result.returnCode = 1;
	}
	printf("LOG: Register method end\n");
	return &result;
}




