/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "loginrpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

resultpair *
login_1(credpair *argp, CLIENT *clnt)
{
	static resultpair clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, LOGIN,
		(xdrproc_t) xdr_credpair, (caddr_t) argp,
		(xdrproc_t) xdr_resultpair, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultpair *
register_1(credpair *argp, CLIENT *clnt)
{
	static resultpair clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, REGISTER,
		(xdrproc_t) xdr_credpair, (caddr_t) argp,
		(xdrproc_t) xdr_resultpair, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
